server:
  port: 8081

spring:
  mongodb:
    uri: mongodb://localhost:27017/transactiondb
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379

app:
  kafka:
    topic: transaction-events

management:
  endpoints:
    web:
      exposure:
        include: health,info
